global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'bot'
    static_configs:
      - targets: ['host.docker.internal:8001']
  - job_name: 'scrapper'
    static_configs:
      - targets: ['host.docker.internal:8000']
