app:
  scheduler:
    enable: true
    interval: 20s
    force-check-delay: 20s
    max-links-per-check: 100
  github-token: ${GITHUB_TOKEN}
  database-access-type: jdbc

supplier:
  github:
    url: "https://api.github.com/"
    patterns:
      repository: "https://github.com/(.+)/(.+)"
  stackoverflow:
    url: "https://api.stackexchange.com/2.3"
    patterns:
      questions: "https://stackoverflow.com/questions/(\\d+).*"

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bot:
  url: http://localhost:8090
