/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private String url;
    private OffsetDateTime lastUpdate;
    private OffsetDateTime lastCheck;
    private String metaInfo;

    public Link() {}

    public Link(Link value) {
        this.linkId = value.linkId;
        this.url = value.url;
        this.lastUpdate = value.lastUpdate;
        this.lastCheck = value.lastCheck;
        this.metaInfo = value.metaInfo;
    }

    @ConstructorProperties({ "linkId", "url", "lastUpdate", "lastCheck", "metaInfo" })
    public Link(
        @Nullable Long linkId,
        @NotNull String url,
        @NotNull OffsetDateTime lastUpdate,
        @NotNull OffsetDateTime lastCheck,
        @Nullable String metaInfo
    ) {
        this.linkId = linkId;
        this.url = url;
        this.lastUpdate = lastUpdate;
        this.lastCheck = lastCheck;
        this.metaInfo = metaInfo;
    }

    /**
     * Getter for <code>public.link.link_id</code>.
     */
    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>public.link.link_id</code>.
     */
    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.link.last_update</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.link.last_update</code>.
     */
    public void setLastUpdate(@NotNull OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.link.last_check</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getLastCheck() {
        return this.lastCheck;
    }

    /**
     * Setter for <code>public.link.last_check</code>.
     */
    public void setLastCheck(@NotNull OffsetDateTime lastCheck) {
        this.lastCheck = lastCheck;
    }

    /**
     * Getter for <code>public.link.meta_info</code>.
     */
    @Nullable
    public String getMetaInfo() {
        return this.metaInfo;
    }

    /**
     * Setter for <code>public.link.meta_info</code>.
     */
    public void setMetaInfo(@Nullable String metaInfo) {
        this.metaInfo = metaInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        if (this.lastCheck == null) {
            if (other.lastCheck != null)
                return false;
        }
        else if (!this.lastCheck.equals(other.lastCheck))
            return false;
        if (this.metaInfo == null) {
            if (other.metaInfo != null)
                return false;
        }
        else if (!this.metaInfo.equals(other.metaInfo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        result = prime * result + ((this.lastCheck == null) ? 0 : this.lastCheck.hashCode());
        result = prime * result + ((this.metaInfo == null) ? 0 : this.metaInfo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(linkId);
        sb.append(", ").append(url);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(lastCheck);
        sb.append(", ").append(metaInfo);

        sb.append(")");
        return sb.toString();
    }
}
